---
title: "PHOIBLE uvular and ejective consonants"
author: "Steven Moran"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: github_document
---

```
Data format for uvulars and ejectives data:

InventoryID | Glottocode | ... | Uvulars | Ejectives | Marginal_Uvular | ...
1 | aaaa1111 | ... | 2 | 4 | 1 | ...

```

```{r, message=F, warning=F}
library(dplyr)
library(knitr)
library(ggplot2)
```

## Data prep

```{r}
# Get PHOIBLE data and merge in Glottolog metadata
# TODO: update to URL
phoible <- read.csv('~/Github/phoible/data/phoible.csv', stringsAsFactors = F)

# Merge in Glottolog 4.1 data (https://glottolog.org/meta/downloads)
languoids <- read.csv('glottolog_languoid.csv/languoid.csv', stringsAsFactors = FALSE) 
geo <- read.csv("languages_and_dialects_geo.csv", stringsAsFactors = FALSE)
phoible <- left_join(phoible, languoids, by=c("Glottocode"="id"))
phoible <- left_join(phoible, geo)
rm(geo, languoids)

# Create phoible index
index <- phoible %>% select(InventoryID, Glottocode, ISO6393, name, LanguageName, SpecificDialect, Source, family_id, level, status, latitude, longitude, country_ids, macroarea) %>% distinct()

index <- index %>% rename(GlottologName = name, PhoibleName = LanguageName)
```

```{r}
# Get uvular consonant counts and the number of marginals
# TODO: What about uvularization of consonants and/or vowels? I.e. < ʶ>
uvulars <- phoible %>% filter(grepl("q|ɢ|ɴ|ʀ|χ|ʁ|ʛ|ʟ̠", Phoneme))
uvular.counts <- uvulars %>% group_by(InventoryID) %>% summarize(Uvulars=n())
uvular.marginals <- uvulars %>% filter(Marginal) %>% group_by(InventoryID) %>% summarize(Marginal_Uvular=n())
```

```{r}
# Note that the features +dorsal and +back don't capture uvulars that are palatalized (negates [back])
t1 <- uvulars %>% select(Phoneme) %>% distinct()
"χʲ" %in% t1$Phoneme
t2 <- phoible %>% filter(back=="+" & dorsal=="+") %>% select(Phoneme) %>% distinct()
"χʲ" %in% t2$Phoneme
setdiff(t1$Phoneme, t2$Phoneme)
rm(t1, t2)
```

```{r}
# Get ejectives counts and the number of marginals
ejectives <- phoible %>% filter(grepl("ʼ", Phoneme))
ejective.counts <- ejectives %>% group_by(InventoryID) %>% summarize(Ejectives=n())
ejective.marginals <- ejectives %>% filter(Marginal) %>% group_by(InventoryID) %>% summarize(Marginal_Ejective=n())
```

```{r}
# Joins
df <- left_join(index, uvular.counts)
df <- left_join(df, uvular.marginals)
df <- left_join(df, ejective.counts)
df <- left_join(df, ejective.marginals)
rm(ejective.counts, ejective.marginals, uvular.counts, uvular.marginals)

write.csv(df, "uvulars_ejectives.csv", row.names = FALSE)
```

```{r}
# Do any languages contain uvulars that are always marginal? Yes.
kable(df[which(df$Uvulars==df$Marginal_Uvular),])
kable(phoible %>% select(InventoryID, Glottocode, LanguageName, Phoneme) %>% filter(InventoryID==354) %>% filter(grepl("q|ɢ|ɴ|ʀ|χ|ʁ|ʛ|ʟ̠", Phoneme)))
```

```{r}
# Do any languages contain ejectives that are always marginal? Yes.
kable(df[which(df$Ejectives==df$Marginal_Ejective),])
kable(phoible %>% select(InventoryID, Glottocode, LanguageName, Phoneme) %>% filter(InventoryID==1276) %>% filter(grepl("ʼ", Phoneme)))
```

## Descriptive

```{r}
# How many Glottocodes are there in phoible?
nrow(phoible %>% select(Glottocode) %>% distinct())

# How many phoible inventories have uvular consonants?
nrow(uvulars %>% select(InventoryID) %>% distinct())

# How many are marginal?
nrow(uvulars %>% filter(Marginal) %>% group_by(InventoryID, Marginal)) # 21 rows
kable(uvulars %>% filter(Marginal) %>% group_by(InventoryID, Marginal))

# How many phoible inventories have ejectives?
nrow(ejectives %>% select(InventoryID) %>% distinct())

# How many are marginal?
nrow(ejectives %>% filter(Marginal) %>% group_by(InventoryID, Marginal)) # 23 rows
kable(ejectives %>% filter(Marginal) %>% group_by(InventoryID, Marginal))
```

## Exploratory

```{r}
# How are uvulars distributed in phoible (across duplicate languages)?
distribution.uvulars <- uvulars %>% group_by(Phoneme) %>% summarize(count=n()) %>% arrange(desc(count))
kable(distribution.uvulars)

# Order the frequency counts and plot the distribution of uvular consonants in the sample
distribution.uvulars$Phoneme <- factor(distribution.uvulars$Phoneme, levels=distribution.uvulars$Phoneme[order(-distribution.uvulars$count)])

# qplot(distribution.uvulars$Phoneme, distribution.uvulars$count)

p <- ggplot(aes(y=count, x=Phoneme), data=distribution.uvulars) +
  geom_bar(stat="identity", width = 0.3, color = "black") +
  xlab("Segments") +
  ylab("# of languages") +
  theme_minimal() +
  ggtitle("")
p
```

```{r}
# How are uvulars distributed in phoible (across duplicate languages)?
distribution.ejectives <- ejectives %>% group_by(Phoneme) %>% summarize(count=n()) %>% arrange(desc(count))
kable(distribution.ejectives)

# Order the frequency counts and plot the distribution of uvular consonants in the sample
distribution.ejectives$Phoneme <- factor(distribution.ejectives$Phoneme, levels=distribution.ejectives$Phoneme[order(-distribution.ejectives$count)])

# qplot(distribution.ejectives$Phoneme, distribution.ejectives$count)

p <- ggplot(aes(y=count, x=Phoneme), data=distribution.ejectives) +
  geom_bar(stat="identity", width = 0.3, color = "black") +
  xlab("Segments") +
  ylab("# of languages") +
  theme_minimal() +
  ggtitle("")
p
```



```{r}
# Distribution of uvular consonants per inventory (can't use Glottocode because there are multiple doculects)
uvulars.counts <- uvulars %>% select(InventoryID, Glottocode, Phoneme, macroarea) %>% group_by(InventoryID, Glottocode, macroarea) %>% summarize(count=n()) %>% arrange(desc(count))

qplot(y=uvulars.counts$count)

# How are they distributed via macroarea
kable(table(uvulars.counts$macroarea))
```

```{r}
# Distribution of ejective per inventory (can't use Glottocode because there are multiple doculects)
ejectives.counts <- ejectives %>% select(InventoryID, Glottocode, Phoneme, macroarea) %>% group_by(InventoryID, Glottocode, macroarea) %>% summarize(count=n()) %>% arrange(desc(count))

qplot(y=ejectives.counts$count)

# How are they distributed via macroarea
kable(table(ejectives.counts$macroarea))
```


