---
title: "Check ER bibliography"
author: "Steven Moran \\<steven.moran@uzh.ch\\>"
output: github_document
---

```{r, message=F, warning=F}
library(bib2df)
library(dplyr)
library(knitr)
library(testthat)
```

# Prepare data

```{r, message=F, warning=F}
# Get ER data.
path <- '../data/raw2019/inventory_biblio.txt'
bib <- bib2df(path)
head(bib)
```

```{r}
# Get ER inventories data. References are made distinct.
er.inv <- read.table("../data/raw2019/Australian_phonemes_for_PHOIBLE_20190118.tsv", sep="\t", quote="\"", header=T, na.strings=c("","NA"), stringsAsFactors = FALSE)
er.inv.d <- er.inv %>% select(Source_ref) %>% group_by(Source_ref) %>% distinct()
expect_equal(nrow(er.inv.d), 232)
kable(head(er.inv.d))
```

# Compare datasets

## How many ER inventory Source_ref's not in the bibtex file?
```{r}
expect_equal(nrow(er.inv.d[which(!(er.inv.d$Source_ref %in% bib$BIBTEXKEY)), ]), 0)
# kable(er.inv.d[which(!(er.inv.d$Source_ref %in% bib$BIBTEXKEY)), ])
```

## How many bibtex IDs not in the ER inventory data?
```{r}
# None
expect_equal(nrow(bib[which(!(bib$BIBTEXKEY %in% er.inv.d$Source_ref)), ]), 0)
```


# Check out PHOIBLE
```{r}
# How many unique er bibtex ids are there per language name?
expect_equal(nrow(er.inv %>% select(Variety_name, Source_ref) %>% distinct()), 392)
```

```{r}
# phoible index data
ph.refs <- read.table("/Users/stiv/Github/dev/mappings/InventoryID-Bibtex.tsv", sep="\t", quote="\"", header=T, na.strings=c("","NA"), stringsAsFactors = FALSE)
# OK to filter on source
expect_equal(ph.refs %>% filter(Source=="er") %>% nrow(), 396)
# Filter
ph.refs.er <- ph.refs %>% filter(Source=="er")
expect_equal(nrow(ph.refs.er), 396)
```

```{r}
# 236 unique bibtex keys in phoible index
expect_equal(nrow(ph.refs.er %>% select(BibtexKey) %>% distinct()), 236)

# 232 unique bibtex keys in ER distinct inventories
expect_equal(nrow(er.inv.d %>% select(Source_ref) %>% distinct()), 232)

x <- ph.refs.er %>% select(BibtexKey) %>% distinct()
y <- er.inv.d %>% select(Source_ref) %>% distinct()

# None of the bibtex IDs match match
table(x$BibtexKey %in% y$Source_ref)
```

```{r}
# Names are diff
head(er.inv.d)
head(ph.refs.er)
```
