---
title: "PHOIBLE phoneme frequencies"
author: "Steven Moran \\<steven.moran@uzh.ch\\>"
output: github_document
---
  
```{r, message=F, warning=F}
library(dplyr)
library(ggplot2)

theme_set(
  theme_bw()
)
```

```{r}
# Get data
phoible <- read.csv('https://raw.githubusercontent.com/phoible/dev/master/data/phoible.csv', stringsAsFactors = F)
# phoible <- read.csv('../../phoible/data/phoible.csv', stringsAsFactors = F)
```

```{r}
# Get cross-linguistic phoneme counts from all inventories
phonemes <- phoible %>% group_by(Phoneme, SegmentClass) %>% summarize(count=n())
phonemes$coverage <- phonemes$count/nrow(phonemes)
phonemes.sorted <- phonemes %>% arrange(desc(coverage))
# phonemes.sorted <- phonemes.sorted %>% head(n=25)
head(phonemes.sorted)
```

```{r}
# temp <- head(phonemes.sorted, n=35)
# cairo_pdf("segment-frequency_files/all_phonemes_35.pdf", family="Helvetica")
temp <- head(phonemes.sorted, n=35)
rownames(temp) <- temp$Phoneme
p <- ggplot(aes(y=coverage, x=reorder(Phoneme, -coverage)), data=temp) +
  geom_point(alpha=0) +
  geom_text(label=rownames(temp)) +
  xlab("Phonemes") +
  ylab("Percentage of data points")
p
```

```{r}
temp <- head(phonemes.sorted, n=100)
rownames(temp) <- temp$Phoneme
p <- ggplot(aes(y=coverage, x=reorder(Phoneme, -coverage)), data=temp) +
  geom_point(alpha=0) +
  geom_text(label=rownames(temp)) +
  xlab("Phonemes") +
  ylab("Percentage of data points") +
  theme(axis.title.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
p
```

```{r}
temp <- head(phonemes.sorted, n=500)
p <- ggplot(aes(y=coverage, x=reorder(Phoneme, -coverage)), data=temp) +
  geom_point() +
  theme(axis.title.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  xlab("Phonemes") +
  ylab("Percentage of data points")
p
```

```{r}
temp <- head(phonemes.sorted, n=250)
p <- ggplot(aes(y=coverage, x=reorder(Phoneme, -coverage)), data=temp) +
  geom_point() +
  theme(axis.title.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  xlab("Phonemes") +
  ylab("Percentage of data points")
p
```

```{r}
temp <- phonemes %>% filter(SegmentClass!="tone")
p <- ggplot(aes(y=coverage, x=reorder(Phoneme, -coverage), fill=SegmentClass, color=SegmentClass), data=temp) +
  geom_point() +
  theme(axis.title.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  xlab("Phoneme rank") +
  ylab("Worldwide frequency of speech sound")
p
```

```{r}
temp <- head(phonemes.sorted, n=220)
temp <- temp %>% filter(SegmentClass=="consonant")
p <- ggplot(aes(y=coverage, x=reorder(Phoneme, -coverage)), data=temp) +
  geom_point() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  xlab("PHOIBLE rank") +
  ylab("Worldwide frequency of speech sounds")
p
```