---
title: "PHOIBLE phoneme frequencies"
author: "Steven Moran"
output: github_document
---
  
```{r, message=F, warning=F}
library(knitr)
library(dplyr)
library(ggplot2)
library(Cairo)

theme_set(
  theme_bw()
)
```

```{r}
# Get data
phoible <- read.csv('https://raw.githubusercontent.com/phoible/dev/master/data/phoible.csv', stringsAsFactors = F)
# phoible <- read.csv('../../phoible/data/phoible.csv', stringsAsFactors = F)
```

```{r}
# Merge in Glottolog data
# Glottolog 3.3 data
# https://cdstar.shh.mpg.de/bitstreams/EAEA0-E7DE-FA06-8817-0/glottolog_languoid.csv.zip
languoids <- read.csv('../data/glottolog_languoid/languoid.csv', stringsAsFactors = FALSE) 
geo <- read.csv(url("https://cdstar.shh.mpg.de/bitstreams/EAEA0-E7DE-FA06-8817-0/languages_and_dialects_geo.csv"), stringsAsFactors = FALSE)

phoible <- left_join(phoible, languoids, by=c("Glottocode"="id"))
phoible <- left_join(phoible, geo)
```

```{r}
# Get cross-linguistic phoneme counts from all inventories
phonemes <- phoible %>% group_by(Phoneme, SegmentClass) %>% summarize(count=n())
phonemes$coverage <- phonemes$count/nrow(phonemes)
phonemes.sorted <- phonemes %>% arrange(desc(coverage))
# phonemes.sorted <- phonemes.sorted %>% head(n=25)
head(phonemes.sorted)
```

```{r}
# All phonemes across all inventories in the full sample
temp <- head(phonemes.sorted, n=35)
cairo_pdf("segment-frequency_files/all_phonemes_35.pdf", family="Helvetica")
p <- ggplot(aes(y=coverage, x=reorder(Phoneme, -coverage)), data=temp) +
  geom_bar(stat="identity", width = 0.3, color = "black") +
  xlab("Phonemes") +
  ylab("Percentage of data points")
print(p)
dev.off()
p
```

```{r}
# All phonemes across all inventories in the full sample - flipped
temp <- head(phonemes.sorted, n=35)
p <- ggplot(aes(y=coverage, x=reorder(Phoneme, coverage)), data=temp) +
  geom_bar(stat="identity", width = 0.3, color = "black") +
  xlab("Phonemes") +
  ylab("Percentage of data points")
p + coord_flip()
```

```{r}
# Get cross-linguistic phoneme counts by grouping all ISO codes
phonemes.per.iso <- phoible %>% group_by(ISO6393, Phoneme) %>% summarize(count=n())
distinct.isos <- phonemes.per.iso %>% select(ISO6393) %>% distinct()
phonemes <- phonemes.per.iso %>% group_by(Phoneme) %>% summarize(count=n())
phonemes$coverage <- phonemes$count/nrow(distinct.isos)
phonemes.sorted <- phonemes %>% arrange(desc(coverage))
# phonemes.sorted <- phonemes.sorted %>% head(n=25)
head(phonemes.sorted)

# Merge in SegmentClass values
segment.class <- phoible %>% select(Phoneme, SegmentClass) %>% distinct()
phonemes.sorted <- left_join(phonemes.sorted, segment.class)
```

```{r}
# All phonemes across all ISOs
temp <- head(phonemes.sorted, n=35)
p <- ggplot(aes(y=coverage, x=reorder(Phoneme, -coverage)), data=temp) +
  geom_bar(stat="identity", width = 0.3, color = "black") +
  xlab("Phonemes") +
  ylab("Percentage of data points")
p
```

```{r}
# All phonemes across all ISOs - flipped
temp <- head(phonemes.sorted, n=35)
p <- ggplot(aes(y=coverage, x=reorder(Phoneme, coverage)), data=temp) +
  geom_bar(stat="identity", width = 0.3, color = "black") +
  xlab("Phonemes") +
  ylab("Percentage of data points")
p + coord_flip()
```


```{r}
# Consonants only
temp <- phonemes.sorted %>% filter(SegmentClass == "consonant") %>% head(phonemes.sorted, n=35)
p <- ggplot(aes(y=coverage, x=reorder(Phoneme, -coverage)), data=temp) +
  geom_bar(stat="identity", width = 0.3, color = "black") +
  xlab("Phonemes") +
  ylab("Percentage of data points")
p
```

```{r}
# Consonants only flipped
p <- ggplot(aes(y=coverage, x=reorder(Phoneme, coverage)), data=temp) +
  geom_bar(stat="identity", width = 0.3, color = "black") +
  xlab("Phonemes") +
  ylab("Percentage of data points")
p + coord_flip()
```

```{r}
# Vowels only
temp <- phonemes.sorted %>% filter(SegmentClass == "vowel") %>% head(phonemes.sorted, n=35)
p <- ggplot(aes(y=coverage, x=reorder(Phoneme, -coverage)), data=temp) +
  geom_bar(stat="identity", width = 0.3, color = "black") +
  xlab("Phonemes") +
  ylab("Percentage of data points")
p
```

```{r}
# Vowels only
temp <- phonemes.sorted %>% filter(SegmentClass == "vowel") %>% head(phonemes.sorted, n=35)
p <- ggplot(aes(y=coverage, x=reorder(Phoneme, coverage)), data=temp) +
  geom_bar(stat="identity", width = 0.3, color = "black") +
  xlab("Phonemes") +
  ylab("Percentage of data points")
p + coord_flip()
```

```{r}
# Summarize how frequent infrequent sounds are
temp <- phonemes.sorted %>% group_by(count) %>% summarize(segments=n())
temp <- temp %>% head(n=10)
p <- ggplot(aes(y=segments, x=reorder(count, -segments)), data=temp) +
  geom_bar(stat="identity", width = 0.3, color = "black") +
  xlab("How many languages they occur in") +
  ylab("Number of segment types")
p
```

```{r}
# Summarize how frequent infrequent sounds are - flipped
temp <- phonemes.sorted %>% group_by(count) %>% summarize(segments=n())
temp <- temp %>% head(n=10)
p <- ggplot(aes(y=segments, x=reorder(count, segments)), data=temp) +
  geom_bar(stat="identity", width = 0.3, color = "black") +
  xlab("How many languages they occur in") +
  ylab("Number of segment types")
p + coord_flip()
```

```{r}
iso.marcoareas <- phoible %>% select(ISO6393, macroarea) %>% distinct()
phonemes.per.iso.with.geo <- left_join(phonemes.per.iso, iso.marcoareas)
phonemes.per.iso.with.geo

# How many data points do we have per macroregion (by ISO code)
x <- phonemes.per.iso.with.geo %>% group_by(ISO6393, macroarea) %>% summarize(count=n())
geo.counts <- x %>% group_by(macroarea) %>% summarise(totals=n())

# 
macro.area.phoneme.counts <- phonemes.per.iso.with.geo %>% group_by(macroarea, Phoneme) %>% summarize(count = n()) %>% filter(macroarea!="")  %>% filter(!is.na(macroarea))

y <- left_join(macro.area.phoneme.counts, geo.counts)
y$coverage <- y$count/y$totals
y

z <- left_join(y, phonemes.sorted, by=c("Phoneme"="Phoneme"))
```

```{r}
# Get top n by area
top.by.area <- z %>% group_by(macroarea) %>% filter(SegmentClass=="consonant") %>% top_n(n = 10, wt = coverage.y)

p <- ggplot(aes(y=coverage.x, x=reorder(Phoneme, -count.y), fill=macroarea), data=top.by.area) +
  geom_bar(stat="identity", width = 0.9, position=position_dodge(0.9)) +
  xlab("Phonemes") +
  ylab("Percentage of data points") +
  scale_fill_manual(values=c(alpha('#4477aa', .8), alpha('#66ccee', .8), alpha('#228833', .8), alpha('#ccbb44', .8), alpha('#ee6677', .8), alpha('#aa3377', .8)))
p
```
```{r}
# Rank with each bar
test <- top.by.area %>% group_by(Phoneme) %>% mutate(counts_rank = rank(-coverage.x)) %>% ungroup()

p <- ggplot(aes(y=coverage.x, x=reorder(Phoneme, -count.y), fill=macroarea, group=counts_rank), data=test) +
  geom_bar(stat="identity", width = 0.9, position=position_dodge(0.9)) +
  xlab("Phonemes") +
  ylab("Percentage of data points") +
  scale_fill_manual(values=c(alpha('#4477aa', .8), alpha('#66ccee', .8), alpha('#228833', .8), alpha('#ccbb44', .8), alpha('#ee6677', .8), alpha('#aa3377', .8)))
p
```

```{r}
# Get top n by area with phonemes on y axis
top.by.area <- z %>% group_by(macroarea) %>% filter(SegmentClass=="consonant") %>% top_n(n = 20, wt = coverage.y)

p <- ggplot(aes(y=coverage.x, x=reorder(Phoneme, count.y), fill=macroarea), data=top.by.area) +
  geom_bar(stat="identity", width = 0.9, position=position_dodge(0.9)) +
  xlab("Phonemes") +
  ylab("Percentage of data points") +
  scale_fill_manual(values=c(alpha('#4477aa', .8), alpha('#66ccee', .8), alpha('#228833', .8), alpha('#ccbb44', .8), alpha('#ee6677', .8), alpha('#aa3377', .8)))
p + coord_flip()
```

```{r}
# Rank with each bar
test <- top.by.area %>% group_by(Phoneme) %>% mutate(counts_rank = rank(coverage.x)) %>% ungroup()

p <- ggplot(aes(y=coverage.x, x=reorder(Phoneme, count.y), fill=macroarea, group=counts_rank), data=test) +
  geom_bar(stat="identity", width = 0.9, position=position_dodge(0.9)) +
  xlab("Phonemes") +
  ylab("Percentage of data points") +
  scale_fill_manual(values=c(alpha('#4477aa', .8), alpha('#66ccee', .8), alpha('#228833', .8), alpha('#ccbb44', .8), alpha('#ee6677', .8), alpha('#aa3377', .8)))
p + coord_flip()
```

```{r}
# Reshape data for phoneme frequency by area
library(reshape2)
head(z)

# Extract worldwide coverage
temp <- as.data.frame(z %>% select(Phoneme, coverage.y) %>% ungroup())
temp <- temp[,2:3]
temp <- temp %>% distinct()

# Recast coverage by area
coverage.by.area <- dcast(z, Phoneme ~ macroarea, value.var = "coverage.x")
coverage.by.area <- left_join(temp, coverage.by.area)

colnames(coverage.by.area) <- c("Phoneme", "Worldwide", "Africa", "Australia", "Eurasia", "NorthAmerica", "Papunesia", "SouthAmerica")

coverage.by.area <- coverage.by.area %>% arrange(desc(Worldwide))
```

```{r}
# By area
p.test <- coverage.by.area %>% head(n=75)
p.test$Phoneme <- factor(p.test$Phoneme, levels = p.test$Phoneme)

ggplot(p.test, aes(Phoneme, group=1)) +
  geom_line(aes(y = Worldwide, colour = "Worldwide"), size=1.5) + 
  geom_line(aes(y = Africa, colour = "Africa")) + 
  geom_line(aes(y = Australia, colour = "Australia")) +
  geom_line(aes(y = Eurasia, colour = "Eurasia")) +
  geom_line(aes(y = NorthAmerica, colour = "NorthAmerica")) +
  geom_line(aes(y = Papunesia, colour = "Papunesia")) +
  geom_line(aes(y = SouthAmerica, colour = "SouthAmerica")) 
```

```{r}
# By area with points
ggplot(p.test, aes(Phoneme, group=1)) +
  geom_line(aes(y = Worldwide, colour = "Worldwide"), size=1.5) + 
  geom_point(aes(y = Africa, colour = "Africa")) + 
  geom_point(aes(y = Australia, colour = "Australia")) +
  geom_point(aes(y = Eurasia, colour = "Eurasia")) +
  geom_point(aes(y = NorthAmerica, colour = "NorthAmerica")) +
  geom_point(aes(y = Papunesia, colour = "Papunesia")) +
  geom_point(aes(y = SouthAmerica, colour = "SouthAmerica")) 
```

```{r}
# Compare genealogically stratied UPSID sample for PHOIBLE

# Get UPSID counts
upsid <- phoible %>% filter(Source=="upsid")
upsid.counts <- upsid %>% select(Phoneme) %>% group_by(Phoneme) %>% summarize(count=n()) %>% arrange(desc(count))
upsid.counts$coverage <- upsid.counts$count/length(unique(upsid$InventoryID))

# Join with PHOIBLE counts
temp <- left_join(phonemes.sorted, upsid.counts, by=c("Phoneme"="Phoneme"))

# Reformaulate Phoneme as an order factor
temp$Phoneme <- factor(temp$Phoneme, levels = temp$Phoneme)
```

```{r}
# Plot all data points
ggplot(temp, aes(Phoneme, group=1)) +
  geom_line(aes(y = coverage.x, colour = "PHOIBLE")) + 
  geom_point(aes(y = coverage.y, colour = "UPSID"))
```

```{r}
# Plot a subset of UPSID and PHOIBLE segments
test <- temp %>% head(n=100)

ggplot(test, aes(Phoneme, group=1)) +
  geom_line(aes(y = coverage.x, colour = "PHOIBLE")) + 
  geom_point(aes(y = coverage.y, colour = "UPSID"))
```