---
title: "Check for errors in PHOIBLE segment conventions"
author: "Steven Moran"
date: "(`r format(Sys.time(), '%d %B, %Y')`)"
output:
  github_document:
  pandoc_args: --webtex
---
  
```{r, message=F, warning=F}
library(dplyr)
library(readr)
library(testthat)
library(knitr)
```

# Overview

Check for segment errors in the [PHOIBLE dev data](https://github.com/phoible/dev).

```{r}
phoible <- read_csv("https://github.com/phoible/dev/blob/master/data/phoible.csv?raw=true")
expect_equal(nrow(phoible), 105460) # https://github.com/phoible/dev/commit/9d21f8fa7d8bb592f6aa6378fb456757354d1441
```

```{r}
# Get a list of unique segments and which sources they appear in
phoneme.source <- phoible %>% select(Phoneme, Source) %>% group_by(Phoneme, Source) %>% distinct()
distinct.segments <- phoneme.source %>% group_by(Phoneme) %>% summarize(Sources=tolower(paste(Source, collapse=";"))) %>% arrange(Phoneme)
expect_equal(nrow(distinct.segments), 3164)
head(distinct.segments)
```

```{r}
# write.csv(distinct.segments, file="distinct-segments.csv", row.names = F)
```

```{r}
# Check for ambigously placed segments, e.g. ring above and below (awful hack here because copy and pasting diacritics in R studio is problematic)
rings.below <- distinct.segments %>% filter(grepl("̥", Phoneme))
rings.above <- distinct.segments %>% filter(grepl("̊", Phoneme))
rings <- rbind(rings.above, rings.below)
rings <- rings %>% arrange(Phoneme)
write.csv(rings, file="rings.csv", row.names = F)

kable(rings)
```

```{r}
# Check for ambigously placed segments, e.g. ring above and below (awful hack here because copy and pasting diacritics in R studio is problematic)
syllabic.below <- distinct.segments %>% filter(grepl("̩", Phoneme))
syllabic.above <- distinct.segments %>% filter(grepl("̍", Phoneme))
syllabic <- rbind(syllabic.above, syllabic.below)
syllabic <- syllabic %>% arrange(Phoneme)
write.csv(syllabic, file="syllabic.csv", row.names = F)

kable(syllabic)
```

