---
title: "What's PHOIBLE's coverage of Glottolog?"
author: "Steven Moran"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
  pandoc_args: --webtex
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, include=FALSE}
library(dplyr)
library(ggplot2)
library(knitr)
library(testthat)
```

# PHOIBLE data
```{r}
phoible.csv <- read.csv(url("https://github.com/phoible/dev/raw/master/mappings/InventoryID-LanguageCodes.csv"),  header=TRUE, stringsAsFactors = FALSE, quote="\"")
glimpse(phoible.csv)
expect_equal(nrow(phoible.csv), 3020) # latest phoible number of data points
```

```{r}
# PHOIBLE inventory data contains duplicate Glottocodes -- remove for coverage analysis
phoible.gcodes <- phoible.csv %>% select(Glottocode) %>% distinct()
expect_equal(nrow(phoible.gcodes), 2185)
```

# Glottolog data
```{r}
load('/Users/stiv/Github/glottolog-scripts/coverage/glottolog-families-isolates.Rdata')
```

# Isolates coverage
```{r}
# Isolates in phoible
isolates$in.phoible <- isolates$id %in% phoible.gcodes$Glottocode
table(isolates$in.phoible)
```

```{r}
# Add macroarea data
isolates <- left_join(isolates, languages.geo)
```

```{r}
# Isolates in and not in phoible
isolates.not.in.phoible <- isolates %>% filter(!in.phoible)
isolates.in.phoible <- isolates %>% filter(in.phoible)
```

```{r}
# Isolates in phoible
ggplot(data=isolates.in.phoible, aes(x=longitude,y=latitude)) + borders("world", colour="gray50", fill="gray50") + geom_point()
```

```{r}
# Isolates NOT in phoible
ggplot(data=isolates.not.in.phoible, aes(x=longitude,y=latitude)) + borders("world", colour="gray50", fill="gray50") + geom_point()
```

```{r}
# isolates in phoible by macroarea
table(isolates.in.phoible$macroarea)
```

```{r}
# isolates not in phoible by macroarea
table(isolates.not.in.phoible$macroarea)
```

## Isolates missing in phoible
```{r}
# Isolates missing in phoible
kable(isolates %>% filter(!in.phoible) %>% select(id, name, isocodes, macroarea), caption = "Isolates not in phoible.")
```

```{r}
# Get phoible coverage for language families
families.glottocodes$in.phoible <- families.glottocodes$id %in% phoible.gcodes$Glottocode
glimpse(families.glottocodes)
```

```{r}
# How many data points in phoible in or not in Glottolog?
table(families.glottocodes$in.phoible)
```

```{r}
# Which Glottocodes are in phoible are not in the Glottolog?
table(phoible.gcodes$Glottocode %in% families.glottocodes$id)
# 216 FALSE -- some may be due to isolates
```

```{r}
# which(!phoible.gcodes$Glottocode %in% families.glottocodes$id)
# phoible.gcodes$Glottocode
```

## Global coverage of phoible
```{r}
in.phoible <- families.glottocodes %>% filter(in.phoible)
ggplot(data=in.phoible, aes(x=longitude,y=latitude)) + borders("world", colour="gray50", fill="gray50") + geom_point()
```

## Languages not in phoible
```{r}
not.in.phoible <- families.glottocodes %>% filter(!in.phoible)
ggplot(data=not.in.phoible, aes(x=longitude,y=latitude)) + borders("world", colour="gray50", fill="gray50") + geom_point()
```

# What kind of macroarea coverage does phoible have?
```{r}
languages.geo$in.phoible <- languages.geo$glottocode %in% phoible.gcodes$Glottocode
table(languages.geo$in.phoible)
```
```{r}
# Get Glottolog macroareas
# This should be filtered in the Glottolog data extraction script, but just in case
languages.geo <- languages.geo %>% filter(level=="language") %>% filter(macroarea!="")
```

```{r}
# Get Glottolog macroarea counts
glottolog.macroarea.counts <- languages.geo %>% group_by(macroarea) %>% summarise(glottolog.count=n())
glottolog.macroarea.counts
```

```{r}
# Get phoible macroarea counts
phoible.macroarea.counts <- languages.geo %>% filter(in.phoible) %>% group_by(macroarea) %>% summarise(phoible.count=n())
```

```{r}
# Join counts and get percentage
macroarea.counts <- left_join(glottolog.macroarea.counts, phoible.macroarea.counts)
macroarea.counts$percentage <- macroarea.counts$phoible.count / macroarea.counts$glottolog.count
kable(macroarea.counts)
# We have very poor coverage of "Papunesia"
```

```{r}
# What's with Australia? There are many data points in phoible that don't seem to match Glottolog
table(phoible.csv$Source)
aus <- languages.geo %>% filter(macroarea=="Australia")
phoible.aus <- phoible.csv %>% filter(Source=="er") %>% distinct(Glottocode)
table(phoible.aus$Glottocode %in% aus$glottocode)
phoible.aus[which(!(phoible.aus$Glottocode %in% aus$glottocode)), ]

# Answer is that these languages don't appear in the geo data and therefore aren't counted... TODO: fix macroarea counts above (they are wrong!).
```

# By language family
```{r}
# Get Glottolog family counts
glottolog.family.counts <- families.glottocodes %>% group_by(family_id) %>% summarize(glottolog.count=n())
# 241 families without isolates (?)

# Add up Glottolog familes and isolates
total.family.count <- nrow(glottolog.family.counts) + nrow(isolates)
```

```{r}
# Get phoible family counts
phoible.family.counts <- families.glottocodes %>% filter(in.phoible) %>% group_by(family_id) %>% summarise(phoible.count=n())
```

```{r}
# How much total family coverage does phoible have?
phoible.total.family.count <- nrow(phoible.family.counts) + nrow(isolates.in.phoible)
phoible.total.family.count
phoible.total.family.count/total.family.count
```

````{r}
# Join the family counts and get percentage
family.counts <- left_join(glottolog.family.counts, phoible.family.counts)
family.counts$percentage <- family.counts$phoible.count / family.counts$glottolog.count
kable(family.counts)
```
