---
title: "Which languages and which segments in PHOIBLE are missing feature vectors?"
author: "Steven Moran"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
  pandoc_args: --webtex
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, include=FALSE}
library(dplyr)
library(ggplot2)
library(knitr)
```

```{r}
# PHOIBLE dev data that includes ER inventories
load('phoible-by-phoneme.RData')

# Get segments missing feature vectors -- assuming that if [high] is NA, then the segment is not specified
df <- mutate(final.data, missing.segment = ifelse(is.na(high), TRUE, FALSE))
rm(final.data)

# TODO: fix the data types in the aggregated data... argh
df$InventoryID <- as.integer(as.character(df$InventoryID))
```

```{r}
# The current aggregated phoible dev data does not contain Glottocodes -- add em via the phoible inventory
phoible.csv <- read.table(url("https://raw.githubusercontent.com/phoible/dev/master/mappings/InventoryID-LanguageCodes.tsv"), sep="\t", header=TRUE, stringsAsFactors = FALSE, quote="\"")

df <- left_join(df, phoible.csv)
glimpse(df)
```

```{r}
# Add in the Glottolog geo data
# See: https://github.com/bambooforest/glottolog-scripts/blob/master/coverage/get_glottolog_data.md
load('glottolog-families-isolates.Rdata')
rm(families.counts, families.glottocodes)
df <- left_join(df, languages.geo, by=c("Glottocode"="glottocode"))
```

```{r}
# Identify which inventories have a missing segment feature vector
missing.ids <- df %>% group_by(InventoryID, Glottocode, LanguageName, Source, latitude, longitude, macroarea) %>% filter(missing.segment) %>% distinct(InventoryID)
```

```{r}
# How many inventories contain segments without features AND no Glottocode?
table(is.na(missing.ids$Glottocode))
```
```{r}
# Which ones?
missing.ids %>% filter(is.na(Glottocode))
```

```{r}
# Of the inventories with missing segment feature vectors (that are not NA Glottocode), where are they?
ggplot(data=missing.ids, aes(x=longitude,y=latitude)) + borders("world", colour="gray50", fill="gray50") + geom_point()
```

```{r}
# And which sources do they belong to?
table(missing.ids$Source)
```

```{r}
# And which areas do they belong to? This shows most are from Erich's Australian database or Dmitry's Eurasian.
table(missing.ids$macroarea)
```

```{r}
# Total number of distinct segments in PHOIBLE
nrow(df %>% select(Phoneme) %>% group_by(Phoneme) %>% unique())
```

```{r}
# Total number of distinct segments without feature vectors. These need to be added... by hand? Argh!
nrow(df %>% filter(missing.segment) %>% select(Phoneme) %>% group_by(Phoneme) %>% unique())
```

```{r}
# Sort languages by number of segments missing feature vectors.
## Get phonemes per inventory counts
phoneme.counts <- df %>% select(InventoryID, Phoneme) %>% group_by(InventoryID) %>% summarize(phoneme.counts = n())
## Get phonemes per inventory counts where their feature vectors are NA
phoneme.counts.missing <- df %>% filter(missing.segment) %>% select(InventoryID, Phoneme) %>% group_by(InventoryID) %>% summarize(phoneme.counts.missing = n())

x <- left_join(phoneme.counts, phoneme.counts.missing)
missing.ids <- left_join(missing.ids, x)
rm(x, phoneme.counts, phoneme.counts.missing)

# How many lanugages have how many missing segments with feature vectors?
table(missing.ids$phoneme.counts.missing)
```

```{r}
# What are the most frequently missing segments?
missing.segment.frequency <- df %>% filter(missing.segment) %>% select(Phoneme) %>% group_by(Phoneme) %>% summarize(segment.frequency = n()) %>% arrange(desc(segment.frequency))
head(missing.segment.frequency)
```

```{r}
missing.segments <- df %>% filter(missing.segment) %>% select(InventoryID, Phoneme)
head(missing.segments)
```

```{r}
# No particular pattern for inventories missing 1 segment. 
# /N/ is purposely under-described for features.
# a-umlaut long knocks out 14 languages
x <- missing.ids %>% filter(phoneme.counts.missing == 1)
y <- left_join(x, missing.segments)
table(y$Phoneme)
```

```{r}
# Fixing 0235 (small letter n with curl) and 0236 (small letter t with curl)
x <- missing.ids %>% filter(phoneme.counts.missing == 2)
y <- left_join(x, missing.segments)
table(y$Phoneme)
```

```{r}
# Shows that once you get to three, there may be three distinct segments in particular languages (like the tones, probably, or the dipthongs with intervening length).
x <- missing.ids %>% filter(phoneme.counts.missing == 3)
y <- left_join(x, missing.segments)
table(y$Phoneme)
```

```{r}
# What's the distribution at the character level? This doesn't show much because it separates the base 
# character(s) and diacritic(s) and it could be the diacritic that isn't specified in HayesPrime.
missing.segment.frequency
chars <- unlist(strsplit(missing.segment.frequency$Phoneme, ""))
table(chars)
chars <- unique(chars)
```

```{r}
s <- read.table(url('https://raw.githubusercontent.com/bambooforest/features/master/segments.csv'), header=T, stringsAsFactors = FALSE, sep="\t")

d <- read.table(url('https://raw.githubusercontent.com/bambooforest/features/master/diacritics.csv'), header=T, stringsAsFactors = FALSE, sep="\t")

# Which characters are in the new input that are not in the HayesPrime features
chars[which(!(chars %in% c(s$segment, d$diacritic)))]
```



